# Generated by Django 6.0.3 on 2026-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('artist', models.CharField(max_length=200, verbose_name='Artysta')),
                ('full_lyrics', models.TextField(verbose_name='Pełny tekst')),
                ('snippet', models.TextField(verbose_name='Fragment do zgadnięcia')),
            ],
        ),
    ]
