# Generated by Django 6.0.3 on 2026-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='second_snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='full_lyrics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='snippet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
